"""empty message

Revision ID: 12aeffa8185e
Revises: 
Create Date: 2024-11-30 14:02:32.366952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12aeffa8185e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('description_ru', sa.String(), nullable=False),
    sa.Column('description_en', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.CheckConstraint('value > 0', name='achievement_value_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('language', sa.Enum('russian', 'english', name='languageorm'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_achievements',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('present_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'achievement_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_achievements')
    op.drop_table('users')
    op.drop_table('achievements')
    op.execute("DROP TYPE languageorm;")
    # ### end Alembic commands ###
